// The starting pitch for huangzhong (黄钟). This is a guess, not a
// measurement of any real bell — tune it by ear against LISTENING.md.
export const HUANGZHONG_HZ = 261.63;

interface Lu {
  name: string;
  num: number;
  den: number;
  ratio: number;
}

function lu(name: string, num: number, den: number): Lu {
  return { name, num, den, ratio: num / den };
}

// The twelve lü: the Pythagorean chain generated by sanfen sunyi (三分损益法),
// reduced into one octave and sorted ascending. Exact fractions from
// DESIGN.md — do not recompute these from memory, do not round.
export const LU_TABLE: Lu[] = [
  lu("黄钟", 1, 1),
  lu("大吕", 2187, 2048),
  lu("太簇", 9, 8),
  lu("夹钟", 19683, 16384),
  lu("姑洗", 81, 64),
  lu("仲吕", 177147, 131072),
  lu("蕤宾", 729, 512),
  lu("林钟", 3, 2),
  lu("夷则", 6561, 4096),
  lu("南吕", 27, 16),
  lu("无射", 59049, 32768),
  lu("应钟", 243, 128),
];

interface Tone {
  name: string;
  ratio: number;
  freq: number;
}

function tone(name: string, num: number, den: number): Tone {
  const ratio = num / den;
  return { name, ratio, freq: ratio * HUANGZHONG_HZ };
}

function doubleTone(t: Tone): Tone {
  return { name: t.name, ratio: t.ratio * 2, freq: t.freq * 2 };
}

interface Bell {
  zhenggu: Tone;
  cegu: Tone;
}

// Bells 1-5: the base octave. zhenggu carries the pentatonic scale
// (宫商角徵羽); cegu carries the two lü outside it — ruibin, yingzhong — a
// third above.
const baseBells: Bell[] = [
  { zhenggu: tone("黄钟", 1, 1), cegu: tone("姑洗", 81, 64) },
  { zhenggu: tone("太簇", 9, 8), cegu: tone("蕤宾", 729, 512) },
  { zhenggu: tone("姑洗", 81, 64), cegu: tone("林钟", 3, 2) },
  { zhenggu: tone("林钟", 3, 2), cegu: tone("应钟", 243, 128) },
  { zhenggu: tone("南吕", 27, 16), cegu: tone("黄钟", 2, 1) },
];

// Bells 6-10: bells 1-5 an octave up. Ratio and freq both x2, exactly.
export const bells: Bell[] = [
  ...baseBells,
  ...baseBells.map((b) => ({
    zhenggu: doubleTone(b.zhenggu),
    cegu: doubleTone(b.cegu),
  })),
];
